### ISSUE TITLE
482. Reports->Plan reports -> Tag Printout by Machine

### ISSUE THREAD

**Issue by Mamta123** [cubensx/cube#12]
Tag printout by m/c

**Comment by hemantbansal** [comment]
Nisha, let me first discuss this with Edward after that you start working on this issue

**Comment by edward123** [comment]
Hemant, when we can discuss on this?

**Comment by edward123** [comment]
now it is Process Type wise, not m/c wise. Pls test at your end. 
![image](https://f.cloud.github.com/assets/4178426/1389001/0aa70e3a-3bcc-11e3-918e-4cdd545bd5f7.png)

**Comment by edward123** [comment]
closed
