### ISSUE TITLE
487. New Plan --Cutting Seq report-Offcut allocation issue

### ISSUE THREAD

**Issue by Mamta123** [cubensx/cube#16]
in cutting seq. Cube should first assign the offcut for stock use,then the rebar.And when we choose the stock,if the stock is not enough,it let us pass,and in cutting seq. report,it will show the stock we use only to cut.

**Comment by hemantbansal** [comment]
" And when we choose the stock,if the stock is not enough,it let us pass,and in cutting seq. report,it will show the stock we use only to cut. " 
This thing is done and let us know the NSX feedback

**Comment by lucas1234** [comment]
"in cutting seq. Cube should first assign the offcut for stock use,then the rebar."is done.
