### ISSUE TITLE
489. Reports->Plan reports-Plan Detail Excel upload

### ISSUE THREAD

**Issue by Mamta123** [cubensx/cube#18]
report requirement for shearline sequence based on descending prod length by run ID/grade and dia/order id, see attachment 16

**Comment by hemantbansal** [comment]
Edward we need discussion on that

**Comment by Nisha123** [comment]
![barlist report](https://f.cloud.github.com/assets/4178334/512063/c572ab20-be18-11e2-949d-487f940374de.jpg)

**Comment by edward123** [comment]
this is not what we want, we want an Excel format. Will wait to see if the plan details is doable for this requirement.

**Comment by edward123** [comment]
closed, refer to issue #39.
