### ISSUE TITLE
352. MIS Reports

### ISSUE THREAD

**Issue by Mamta123** [cubensx/cube#23]
Refer to the attachment 10 for the required MIS reports in NSX

**Comment by aprajita123** [comment]
Three MIS report completed and one Pending.

**Comment by hemantbansal** [comment]
May i know NSX feedback on this

**Comment by aprajita123** [comment]
MIS All done

**Comment by edward123** [comment]
1. MESH - Material Usage Machine Wise, no produciton weight for SNC
   ![image](https://f.cloud.github.com/assets/4178426/652239/6170c6ae-d49b-11e2-9cc5-40fb7fef04b6.png)
2. MESH - Machine and Product Wise, no record for 20 tons
   ![image](https://f.cloud.github.com/assets/4178426/652257/5bc18ecc-d49c-11e2-9dc4-b4e0a3e612ca.png)

**Comment by aprajita123** [comment]
MESH - Machine and Product Wise report corrected.

**Comment by edward123** [comment]
add grand total for welding m/c 
![image](https://f.cloud.github.com/assets/4178426/1071924/94a161b0-1482-11e3-8f17-a11ffb2a6e10.png)

**Comment by aprajita123** [comment]
Done
