### ISSUE TITLE
WP Batch file Upload

### ISSUE THREAD

**Issue by Mamta123** [cubensx/cube#24]
Upload Function to upload Upstream Heat & Batch Detail from Excel File provided.

Batch no.   Heat no.    Dia Bartype and Grade
Q10000-13   3303097 Φ8 HPB235
Q10001-13   3303098 Φ8 HPB235
Q10002-13   3303099 Φ8 HPB235
Q10003-13   3303100 Φ8 HPB235

Please find the excel in our shared Folder 
CuBe_NSX\WP

**Comment by Mamta123** [comment]
Done
@edward123 please test this once new release is sent to you

**Comment by edward123** [comment]
1. loaded attached excel file to cube
   ![image](https://f.cloud.github.com/assets/4178426/1395981/10e0834a-3c4d-11e3-88cb-332e8f491973.png)
2. key in batch no. Q10000-13 in cube, other 3 info cannot pop up, like heat no.,grade and dia. 
   ![image](https://f.cloud.github.com/assets/4178426/1395986/56bf8f00-3c4d-11e3-8396-97e04f1c98ca.png)

**Comment by Mamta123** [comment]
1.Only three records are inserted,since its reading from 3 row Q10000-14 batch no.
2. Tested for Q10000-14,its working fine
3. Will change starting row logic

**Comment by edward123** [comment]
1. cannot search for previous WP batch ID, eg. W131105001.
   ![image](https://f.cloud.github.com/assets/4178426/1488578/84c823e2-474e-11e3-9242-4029a520ca70.png)
   but WP tag print can find out W131105001.
   ![image](https://f.cloud.github.com/assets/4178426/1488580/9fa882a6-474e-11e3-80aa-807964fa53aa.png)
2. Diameter is showing wrongly for raw material, see RawMatlNo in FINISHED GOODS COIL LIST.
   ![image](https://f.cloud.github.com/assets/4178426/1488592/45a2cb08-474f-11e3-817a-e095bdaca204.png)
   ![image](https://f.cloud.github.com/assets/4178426/1488595/69d454a6-474f-11e3-8985-7d13fccd395c.png)

**Comment by edward123** [comment]
Mamta, just simplify it - implement download to excel facility
[2:21:36 PM] Edward Hong: still we need you to make some improvement:
[2:22:57 PM] Edward Hong: 1. raw matl dia issue - a. you can extract dia from uploading excel file; b. pls rectify dia in RawMatlNo column
[2:30:14 PM] Edward Hong: 2. no need to include Coil No both in RMBatchNo and WPBatchNo, like Q10000-21-02 and W13110007-02 to be changed as Q10000-21 and W13110007.
[2:33:25 PM] Edward Hong: 3. no need to default input for WPBatchNo, we'll key in mamually, like C0001-13. Here C stands for cold-rolled, 13 means Y2013.
[2:37:13 PM] Edward Hong: 4. to add bartype in WPMatlNO, especially when we key in CPB/CRB550.

**Comment by edward123** [comment]
download to Excel facility done. 
point 1. a- resolved, b - unresolved, actually we keyed in diameter 8 instead of 6. 
![image](https://f.cloud.github.com/assets/4178426/1520705/89e285d4-4b81-11e3-9644-704d5905e9e6.png)

point 2/3/4 - remaining

**Comment by Mamta123** [comment]
Done point 2- Removed coil no. both from RMBatch & WPBatch
Point 3 - Disabled auto population feature
Point 4 - Changed Format Of WPMatNo to show BartypeGrade

**Comment by edward123** [comment]
R u sure all of them have been resolved in R5.4.5? From what i have tested, none of them has been resolved, see the highlighted one. 
![image](https://f.cloud.github.com/assets/4178426/1529651/3db37438-4c3b-11e3-8171-d398b6fd2bd7.png)

**Comment by edward123** [comment]
closed in R5.4.6.
