### ISSUE TITLE
Change in DO Format

### ISSUE THREAD

**Issue by Mamta123** [cubensx/cube#26]
[12:26:28 PM] Edward Hong: we have some change for DO format
[12:31:27 PM] Edward Hong: not sure if you have seen upstream SO using the carbon paper, right now we're required to provide customer with DO from cube using same carbon paper
[12:31:41 PM] Edward Hong: so need to make some change of the DO format
[12:38:21 PM] Edward Hong: 1. remove company logo and info
2. change 合同编号 to 销售单号（Upstream SO, derived from SAP order ID in order details. Currently, this column is Contract ID.)(for point 2, it's Contract ID currenlty, and we need to change to SAP order ID)
3. remove Page no. in the header, and add page no. on bottom right corner
4. remove above header in 2nd page onwards, remain such header in first page(Header only on fiorst page)
5. remove this line, see image -IMG_03052013_152247.png
6. shape code needs to display image rather than code no.
7. change these two columns to 总支数 and 总重量（理据）separately-IMG_03052013_153848.png.png
8. for this remark, need to expand the space coz 2nd line cannot print out
Images are in our shared Folder `CuBe_NSX\New Req\DO_Format
9. pls narrow all the columns, and change layout from landscape to portrait so that we can have as many lines as possilbe in one page
10. remove this part at last page, and move both two signatures to left(IMG_03052013_154532.png)

**Comment by Mamta123** [comment]
1. change these two columns to 总支数 and 总重量（理据）separately-
2. remove this part at last page, and move both two signatures to left

These two points are not clear

**Comment by edward123** [comment]
1. in English version, we have Total Nos and Delivered Qty(T), so pls change the equivalent Chinese to 总支数 and 理计重量（吨）separately， as well as in product summary.
2. the vehicle part info, pls delete first 3 info(vehicle no. w/t no. and LL no.)  and keep the site contact person and Project Coordinator. 
3. Meanhwile, delete from time and to time

**Comment by edward123** [comment]
1. shape image doesn't show the detailed figure of that shape, only parameter A B C D. 
   But just hold on the improvement until we confirm.

**Comment by Mamta123** [comment]
Edward,I think DO doesn't need the detail information.waiting for your feedback

**Comment by sunitmishra** [comment]
completed
