### ISSUE TITLE
Bar List per m/c - every m/c should have a total production weight

### ISSUE THREAD

**Issue by edward123** [cubensx/cube#27]
Right now, only the overall run ID have a total production weight. But it's inconvenient for production to prepare the raw mtl since they're unable to read the total production weight by each m/c direclty. So pls add the total production weight by each m/c in the header.

**Comment by Nisha123** [comment]
Done.

**Comment by edward123** [comment]
each dia shall have a sub total production weight as well in each m/c; that means each m/c has a total prod weight, within which each dia has a sub total prod weight.

**Comment by Nisha123** [comment]
Done.
