### ISSUE TITLE
Loading Advice For CAB in Chinese

### ISSUE THREAD

**Issue by Mamta123** [cubensx/cube#30]
New Format for LA in chinese has been provided by Edward.

**Comment by Mamta123** [comment]
Feedback from Edward:-
1. logo has a dark outter line, could we remove it
2. we want customer name, not customer Prefix
3. delivery date  should be chinese date format(change it as 2013/5/17)

**Comment by edward123** [comment]
1. change the main title as 钢筋深加工/焊接网提货明细

**Comment by aprajita123** [comment]
Customer prefix changed to Customer name.
Delivery date changed to Chinese data format .
logo changed.
Main title  changed.

**Comment by edward123** [comment]
1. pls change the printout format from landscape to portrait
2. from 2nd page onwards, shall have the header(the one includes shape image, barmark ID, tag id, pcs, weight, etc)

**Comment by aprajita123** [comment]
Format changed to portrait. and 2nd page on wards header is included in report.
