### ISSUE TITLE
Shearline Improvement submitted by Lucas

### ISSUE THREAD

**Issue by edward123** [cubensx/cube#33]
1. use IBL at first priority, then 12m. Pls note currently we need to take as much IBL as possible for optimization. 
2. cutting sequence report should be showed sequence based on RM length ascending - IBL first, then 12m, don't mix up IBL and 12m. 
3. same FG length between different Comb number should be able to disply together, don't mix up with other length.

**Comment by edward123** [comment]
addition:
1. offcut length wont be showing in LED screen, but showing 12m all the time. 
2. In cutting sequence, when producing Comb No.1, the cutting length was not Comb No. 1, but Comb No. 2 or 3. meaning it will be jumping.

**Comment by lucas1234** [comment]
Please see issue #42
