### ISSUE TITLE
add process time in bar list per m/c per grade

### ISSUE THREAD

**Issue by edward123** [cubensx/cube#34]
operator shall follow such process time and make sure order can be completed in time.

**Comment by Nisha123** [comment]
Done. plz check with release # 5.4.1.

**Comment by edward123** [comment]
1. Start and End time are incorrect. 
   ![image](https://f.cloud.github.com/assets/4178426/1349721/093ee51e-36f8-11e3-8c4d-e616fe86dcbe.png)
2. Currenlty it's by m/c wise only, pls amend it by grade and diameter wise as well.

**Comment by edward123** [comment]
done in release 5.4.2
