### ISSUE TITLE
Invoice weight in LA CH version

### ISSUE THREAD

**Issue by edward123** [cubensx/cube#37]
invoice wt in LA header does not tally with total orders weight

**Comment by Mamta123** [comment]
Since One LL contains different Order ID with different SAP Order ID so inv wt was not correct,Now as disscussed with Edrward,following changes to be made

--> IF SAP Order ID is more then one then it should be Comma seperated.

**Comment by aprajita123** [comment]
Change has been made in LA _CH Report.
