### ISSUE TITLE
Plan Detail Based on Elements -- in excel

### ISSUE THREAD

**Issue by Mamta123** [cubensx/cube#39]
1.Plan Details in Excel for all orders in one plan based on Elements.

**Comment by aprajita123** [comment]
Completed..

**Comment by aprajita123** [comment]
![plandlt](https://f.cloud.github.com/assets/4264290/589398/196ebaec-c9b9-11e2-8425-49c741b3bce9.jpg)

**Comment by edward123** [comment]
unable to test in latest release.
![image](https://f.cloud.github.com/assets/4178426/652802/c1f56d02-d4c0-11e2-940a-ffec50541fec.png)

**Comment by edward123** [comment]
1. first plan is unable to select
2. barmark id to show text only. 
   ![image](https://f.cloud.github.com/assets/4178426/719974/bcea009e-dfa5-11e2-8134-706a9e3a7393.png)
   ![image](https://f.cloud.github.com/assets/4178426/719978/0b7355c6-dfa6-11e2-94d5-380d4fba2560.png)

**Comment by edward123** [comment]
1. closed. 
2. reopen

**Comment by edward123** [comment]
1. Text for BarMark ID is doable. Need to add it for shape ID, expecially shape ID 0000.

**Comment by edward123** [comment]
Text for shape ID 0000 was resolved.
