### ISSUE TITLE
PRODUCTION UPLOADING 

### ISSUE THREAD

**Issue by lucas1234** [cubensx/cube#44]
![image](https://f.cloud.github.com/assets/4179992/741419/4ef30cdc-e3a8-11e2-8696-1ecfd9149aa2.png)

When I choose one of the the material to upload, cube can't let me pass,but when choose another stock(enough),and have one blank key in "0" ,I pass.Why?

2013.7.9
![image](https://f.cloud.github.com/assets/4179992/766002/c209adbc-e848-11e2-94c0-3aeb61f2a0e4.png)

**Comment by Mamta123** [comment]
Yes you need to keyin 0 for all other fields

**Comment by edward123** [comment]
Even key in 0 for all other fields, error msg pops up. But we would expect those zero stock doesn't need to show in Prod Uploading. 
![image](https://f.cloud.github.com/assets/4178426/786041/9cb9a978-ea9a-11e2-8366-ec4858a96c5b.png)

Msg from log:

Date Time Stamp : 7/12/2013 10:27:19 AM
Source of error :    在 System.Data.OleDb.OleDbCommand.ExecuteReaderInternal(CommandBehavior behavior, String method)
   在 System.Data.OleDb.OleDbCommand.ExecuteNonQuery()
   在 CuBe.t_tool.updatequery(String strupdate) 位置 D:\ApCuBeVSS\6 July CuBe NSX\CuBe_v2.0.root\CuBe_v2.0\CuBe\t_tool.vb:行号 63
   在 CuBe.frmProductionUploading.btnConfirm_Click(Object sender, EventArgs e) 位置 D:\ApCuBeVSS\6 July CuBe NSX\CuBe_v2.0.root\CuBe_v2.0\CuBe\frmProductionUploading.vb:行号 558
Error Details : Error converting data type varchar to numeric.

**Comment by edward123** [comment]
issue resolved
