### ISSUE TITLE
3D shpae(like bar chair) should not be assigned to double bender. 

### ISSUE THREAD

**Issue by edward123** [cubensx/cube#45]

**Comment by hemantbansal** [comment]
CTD_PLAN_ID CTD_ORDER_ID    CTD_ELEMENT_ID  CTD_ITEM_ID CTD_TAG_ID  CTD_SEQTAG_ID   CID_SHAPE_ID    CSM_NO_BEND CTD_PB_MC_ID    CTD_SHEARING_MC_ID  CTD_SAW_MC_ID   CTD_COUPLER_MC_ID   CTD_RB_MC_ID    CTD_BENDING_MC_ID  
PL-20130525-009 FXDSM1305CA37   2   20  18  27  4013    4   -1  1   -1  -1  -1  4  
PL-20130525-009 FXDSM1305CA37   4   62  39  59  4013    4   -1  1   -1  -1  -1  4  
PL-20130602-004 FXDSM1306CA01   1   26  35  42  4013    4   -1  1   -1  -1  -1  4  
PL-20130602-004 FXDSM1306CA01   1   27  36  43  4013    4   -1  1   -1  -1  -1  4  
PL-20130607-004 FXXHM1306CA14   1   4   4   6   4013    4   -1  1   100 100 -1  4
