### ISSUE TITLE
Mesh Tag edit issue

### ISSUE THREAD

**Issue by lucas1234** [cubensx/cube#48]
![5](https://f.cloud.github.com/assets/4179992/747287/ebc22bf8-e455-11e2-8315-9286e25df131.jpg)

can't key in the value directly,should use mouse to click!

2013.07.24
![qq20130724104914](https://f.cloud.github.com/assets/4179992/846334/03669814-f40c-11e2-87f1-0e3994645aba.jpg)

when I want to edit tag,don't let cube change any information I selectd before,or I will select one more time(ex:I selectd CRB,but now it is CPB),I only need to change the value I want to change

**Comment by Mamta123** [comment]
after Shape Id please press enter key.it will start from that cell

**Comment by edward123** [comment]
how about point 2?
