### ISSUE TITLE
WELDING PRODUCTION SCHEDULE SUMMARY MESH ISSUE

### ISSUE THREAD

**Issue by lucas1234** [cubensx/cube#49]
![23](https://f.cloud.github.com/assets/4179992/747345/ff8e9ce0-e458-11e2-989b-995257f53e42.jpg)

the same length cross wire should be assigned together from long to short.cross wire assigned first then main wire for welding machine report~

**Comment by edward123** [comment]
pls sort out by tag id

![image](https://f.cloud.github.com/assets/4178426/818021/7dba75de-ef86-11e2-9bd9-bcd34e74a613.png)

Hemant advised to maintain the sequence for Welding in Production Schedule Report, but currently this functionality is only for SNC, not for Welding. 

![image](https://f.cloud.github.com/assets/4178426/818128/77f39fec-ef89-11e2-964d-39dd36b8e1f1.png)

**Comment by edward123** [comment]
unresolved in UAT
![image](https://f.cloud.github.com/assets/4178426/1013922/c5788aa2-0b9f-11e3-8221-47034b03f772.png)

**Comment by hemantbansal** [comment]
UAT Database , Plan Id PL-20130823-001, Order Id MESH1308MA07, 
23 Aug, Day Shift,
Schedule Summary Report, Welding Process, GWC2800 Machine

**Comment by Nisha123** [comment]
Done
