### ISSUE TITLE
report bar list per machine(mesh)

### ISSUE THREAD

**Issue by lucas1234** [cubensx/cube#50]
![12](https://f.cloud.github.com/assets/4179992/747377/1a03b9e6-e45b-11e2-8687-7b01ef1c1915.jpg)

We don't need to show prod wt. and inv wt. for single tag in this report,so please delete them,you have showed total in the top.
you need to add real prod mo/mo ,co/co and the length of  A and B(for shape 1C1) for single tag in this report,because you haven't added bar list per machine for mesh-bender in cube.

2013.07.23
![1](https://f.cloud.github.com/assets/4179992/839007/074c215e-f332-11e2-8d57-c319a08cc8a0.jpg)
1.No overhand information,please Resolve.
2.If we have the Grade an Dia. in the top,Cube doesn't need to show it in every Tag below.

2013.08.06
![1](https://f.cloud.github.com/assets/4179992/915644/ee1d0d26-fe74-11e2-846e-736683cd15de.jpg)
![image](https://f.cloud.github.com/assets/4179992/915663/6e5a3360-fe75-11e2-8d9a-b0e1cf03624e.png)
1.add product code and mw/cw spacing in the top(the sequence is product code---dia.(mm)---mw/cw spacing)  .
2.cw oh1 should be 84 for prod. length but not 100,please according to prod len.
3.show mw/cw no. for one piece!

2013.08.09
![qq20130809093234](https://f.cloud.github.com/assets/4179992/935867/8ae8e72c-0093-11e3-9a37-ee043169b241.jpg)
![qq20130809093249](https://f.cloud.github.com/assets/4179992/935869/8c6d5902-0093-11e3-9eb5-3783d5d957f6.jpg)
1.Tag Id 006/007 shape code E6 ,NOT A6
2.co1/co2 issue for 2 bends mesh!

**Comment by lucas1234** [comment]
highlight.please assist !         reslove it as fast as you can!!!you only remove the Prod wt.and Inv. wt.

**Comment by Nisha123** [comment]
Done.

**Comment by edward123** [comment]
reopen, for U shape MESH, example shape 2C1, CO1 and CO2 shall be same value 32, not 14/50. Pls check.
![image](https://f.cloud.github.com/assets/4178426/1013929/23a3aa08-0ba0-11e3-9933-653f021f18d9.png)

**Comment by Nisha123** [comment]
Done. plz test with next release.

**Comment by edward123** [comment]
pending for new requirement - need to add production segment length for A/B/C example - A 182, B 2000, C 182.

**Comment by edward123** [comment]
CO1 and CO2 shall be actual production length 82/82, not 100/100. As to segment lenght A B C, they're decided by bending way, example if bending by sequence ABC, respective ABC length will be 200, 2000, 164; if bending by sequence ACB, that length will be 200, 1964, 200. 
![image](https://f.cloud.github.com/assets/4178426/1365794/912a934e-3890-11e3-9fc9-6248332359a8.png)

**Comment by Mamta123** [comment]
How to know the bending sequence.Coz for different shapes bending sequence may be different,.Then how to ensure that lengths A,B & C are showing correct Prod len. As now it is showing Invoice Length.

**Comment by edward123** [comment]
## As per discussion, Mamta will be implementing following logic for actual production OH and actual segment length(ABC). 

1) Please note our machine only able to produce spacing 100 with 50mm steps increasing, therefore, no way to change the line spacing to 182.

Therefore, if have bending, i propose the logic as below:

OH1 - total creep length

Eg for this case, theoriticle oh=100/100, production oh - 64/100

2) We request the actual bending length to appear on report,

Eg for this case, (B>1000mm), so bending sequence is A,C,B, we want Bar List to appear A-182, B-2000,C-182, so after elongation, the FG should have U shape with A=C=200

If B=<1000mm, we prefer bending from A then B, so elongation will gose to the A, and B, therefore A should bend at 182mm, B at 1982, C=200.

**Comment by Nisha123** [comment]
Done.

**Comment by edward123** [comment]
From attached image, CW OH1 should be 14. Pls note following script from Skype
sorry, I meant since we can NOT change the spacing of MAIN wire.
[10:31:11 AM] Edward Hong: just calculate, CW OH1+2=32+50=82, CW Prod Length 1164, then 1164-82/100=10.82, that means we have to chagne MW spacing. But you know we cannot change.
[10:39:51 AM] Edward Hong: Segment B is not directly related with OH, same as other segments. OH is only related with spacing.
![image](https://f.cloud.github.com/assets/4178426/1529665/cef45976-4c3b-11e3-9274-6971c195817e.png)

**Comment by Nisha123** [comment]
ok Edward, got your point. i have changed the logic accordingly and will send with the release 5.4.6.

**Comment by edward123** [comment]
closed it in R5.4.6.
