### ISSUE TITLE
Double Bender recipe file downloading issue

### ISSUE THREAD

**Issue by edward123** [cubensx/cube#51]
1. recipe file generation problem
   File name doesn't tally with tag data. It should show actual bar code number as rcp file name. Take RUN ID C-130703-002 for example in Prod DB. 
2. drawing incorrect in rcp file
   from rcp file:
   ![image](https://f.cloud.github.com/assets/4178426/748642/b694f5ee-e48e-11e2-8c03-e8559dffdbc8.png)
   correct one:
   ![image](https://f.cloud.github.com/assets/4178426/748644/b809a2e4-e48e-11e2-952b-a0bc8fca357e.png)

**Comment by edward123** [comment]
sorry, correct one image should be as following:

![image](https://f.cloud.github.com/assets/4178426/759864/d7c05644-e79c-11e2-8973-40aa1aff8ef6.png)

**Comment by Mamta123** [comment]
Please draw all shape from left to right.And retry it.

**Comment by cubensx** [comment]
Please close this. As for new requirement in which MSL >9600,it was agreed that since this type of order volume is less so no need to modify the rcp file.

**Comment by edward123** [comment]
Sorry, Mamta, i checked the chat history in Skype. I think Lucas misunderstood my thought. What i was trying to say is to ignore those more than 2 bends given CSL>9600, but we still need those CSL>9600 with one or two bends.

**Comment by edward123** [comment]
workable now.
