### ISSUE TITLE
tag issue

### ISSUE THREAD

**Issue by lucas1234** [cubensx/cube#52]
![image](https://f.cloud.github.com/assets/4179992/779816/b00206fe-e9ed-11e2-8819-b977fe36ce03.png)
could you change the project ID to project name,this tag is given to customer,project ID is meaningless.Could you change “25.0-2500-50”,to “25.0mm-2500 mm-50 pcs” or “25.0mm-2500 mm-50 支”，yes, add units!

2013.07.23
![2](https://f.cloud.github.com/assets/4179992/839043/6e750cdc-f333-11e2-81ed-b85ec3bdb55a.jpg)

Please show the CW&MW quantity by one picece of mesh but not total number of mesh.

**Comment by lucas1234** [comment]
For 2013.07.23.Please resolve it first!!we have a big project next week,please assist!!!

**Comment by Mamta123** [comment]
![meshtag](https://f.cloud.github.com/assets/4178293/900485/627f0772-fb65-11e2-966c-f5eddf0e53ce.png)

**Comment by Mamta123** [comment]
Done please check

**Comment by lucas1234** [comment]
well done!
