### ISSUE TITLE
Add and change THREE m/c in cube - new double bender due date 7th Aug

### ISSUE THREAD

**Issue by edward123** [cubensx/cube#53]
1. convert radial bender to both manual bender and radial bender
2. add one manual cutter
3. add one new double bender from Italy

**Comment by edward123** [comment]
Hemant, how about Manual Cutter?

**Comment by edward123** [comment]
Hemant, how about first one - to convert RMS#18 curve bender to both Manual bender and Radial bender.

**Comment by hemantbansal** [comment]
Hi Edward , these 3 machines are added in UAT , Please test

**Comment by edward123** [comment]
closed #53, remaining manual cutter issue will refer to #63.
