### ISSUE TITLE
add project name under customer name in loading advice

### ISSUE THREAD

**Issue by edward123** [cubensx/cube#78]
The equivalent Chinese of project name is 项目名称.
![image](https://f.cloud.github.com/assets/4178426/1817418/194267fa-6f9d-11e3-8429-fe8a91eb8907.png)

**Comment by aprajita123** [comment]
Done

**Comment by edward123** [comment]
Project Name does not tally between Loading List and Loading Advice. 
![image](https://f.cloud.github.com/assets/4178426/1837159/3e1c4668-7420-11e3-9548-964bd7c94855.png)
![image](https://f.cloud.github.com/assets/4178426/1837161/57b51e06-7420-11e3-9965-5e360af40774.png)

**Comment by aprajita123** [comment]
Closed

**Comment by edward123** [comment]
closed in R5.5.2.
