### ISSUE TITLE
add Project Name beside Order ID in order summary

### ISSUE THREAD

**Issue by edward123** [cubensx/cube#80]
![image](https://f.cloud.github.com/assets/4178426/1826617/a453662a-7202-11e3-9acb-2b8f290bdcdd.png)

**Comment by aprajita123** [comment]
Done

**Comment by edward123** [comment]
closed in R5.5.1. Project Name in order summary is correct. 
![image](https://f.cloud.github.com/assets/4178426/1837176/bebafab2-7420-11e3-9ea5-834df8a52d34.png)
