### ISSUE TITLE
Number of digits for Project Name in Loading Advice

### ISSUE THREAD

**Issue by edward123** [cubensx/cube#84]
How many digits are allowed to key in Project Name in Loading Advice? Pls enlarge the space to allow 15 digits keyed in.  
![image](https://f.cloud.github.com/assets/4178426/1926992/441d7bd4-7e4f-11e3-9915-9dec85c1cc5e.png)

**Comment by aprajita123** [comment]
Done

**Comment by edward123** [comment]
closed in R5.5.3.
