### ISSUE TITLE
change Remarks in Loading Advice

### ISSUE THREAD

**Issue by edward123** [cubensx/cube#86]
to change Remarks as previous LA version as following, meanwhile pls zoom out the image and show the full name of logo, it's better to remove the dark text box. 
![image](https://f.cloud.github.com/assets/4178426/1937606/aa226602-7f2a-11e3-85c0-0e12d1869351.png)

**Comment by edward123** [comment]
And Mamta, remember to enlarge Remark column so that we can key in enough words

**Comment by edward123** [comment]
Mamta, how is the status of this issue? I think you have resolved it, right?

**Comment by aprajita123** [comment]
Done in Release 5.5.4

**Comment by edward123** [comment]
1. logic has been changed, but pls enlarge this whole part so that remark column could have enough space. 
2. pls zoom out the logo.

**Comment by edward123** [comment]
1. done
2. pls try to zoom out the logo
3. For MESH LA, pls change the format from landscape to portrait, and MESH LA shall have the same   space for remark column.

**Comment by edward123** [comment]
Mamta, how about this issue?

**Comment by edward123** [comment]
UOM issue in R5.5.7.1 Prod database. 
![image](https://cloud.githubusercontent.com/assets/4178426/3492502/351a9c46-05ab-11e4-9999-22b6d7433b5d.png)
